# Generated by Django 5.1.6 on 2025-03-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
