# Generated by Django 5.1.6 on 2025-03-30 15:47

import django.db.models.deletion
import healthapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumsubscription',
            name='premium_expiry',
        ),
        migrations.AddField(
            model_name='customuser',
            name='ai_tries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='expires_at',
            field=models.DateTimeField(default=healthapp.models.default_expiry),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('m', 'm'), ('f', 'f'), ('o', 'o')], max_length=10),
        ),
        migrations.AlterField(
            model_name='premiumsubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
