# Generated by Django 5.1.6 on 2025-03-31 11:43

import healthapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_remove_premiumsubscription_premium_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(default=healthapp.models.default_coupon_expiry),
        ),
    ]
