# Generated by Django 5.1.6 on 2025-04-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_alter_coupon_coupon_code_alter_coupon_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='ai_interpretation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
