# Generated by Django 5.1.6 on 2025-04-01 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0004_alter_medicalhistory_ai_interpretation'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='appointment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthapp.appointment'),
        ),
    ]
