# Generated by Django 5.1.6 on 2025-04-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0005_medicalhistory_appointment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='appointment_id',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='patient',
            new_name='user',
        ),
    ]
