# Generated by Django 5.1.6 on 2025-04-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0006_rename_appointment_id_medicalhistory_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('finished', 'Finished'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
