# Generated by Django 5.1.6 on 2025-04-03 00:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='status',
            field=models.CharField(choices=[('deployed', 'Deployed'), ('archived', 'Archived')], default='deployed', max_length=10),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
