# Generated by Django 5.1.6 on 2025-04-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0008_aimodel_created_at_alter_aimodel_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='version',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='model_file',
            field=models.FileField(default='empty', upload_to='models/'),
            preserve_default=False,
        ),
    ]
