# Generated by Django 5.1.6 on 2025-04-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0009_remove_aimodel_version_aimodel_model_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='ai_interpretation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
