# Generated by Django 5.1.6 on 2025-04-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0010_alter_medicalhistory_ai_interpretation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='ai_interpretation',
            field=models.JSONField(blank=True, default='empty'),
            preserve_default=False,
        ),
    ]
