# Generated by Django 5.1.6 on 2025-04-04 14:33

import healthapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0012_alter_medicalhistory_ai_interpretation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='scan',
            field=models.ImageField(upload_to=healthapp.models.user_scan_upload_path),
        ),
    ]
