# Generated by Django 5.1.6 on 2025-04-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('ai_result', 'Ai Result'), ('message', 'Message'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
