# Generated by Django 5.1.6 on 2025-04-12 23:22

import healthapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0017_customuser_pic_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(null=True, upload_to=healthapp.models.user_pic_upload_path),
        ),
    ]
