# Generated by Django 5.1.6 on 2025-04-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0019_appointeddoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointeddoctor',
            name='external_id',
            field=models.CharField(default='NULL', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
