# Generated by Django 5.1.6 on 2025-04-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0020_appointeddoctor_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointeddoctor',
            name='contact_number',
        ),
    ]
