# Generated by Django 5.1.6 on 2025-04-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0021_remove_appointeddoctor_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
