# Generated by Django 5.1.6 on 2025-04-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0023_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('failed', 'failed'), ('pending', 'pending')], default='completed', max_length=20),
        ),
    ]
