# Generated by Django 5.1.6 on 2025-05-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0024_alter_customuser_phone_number_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointeddoctor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='status',
            field=models.CharField(choices=[('deployed', 'Deployed'), ('vip', 'Vip'), ('archived', 'Archived')], default='deployed', max_length=10),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
