# Generated by Django 5.1.6 on 2025-05-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0025_appointeddoctor_status_alter_aimodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointeddoctor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], max_length=20),
        ),
    ]
