# Generated by Django 5.1.6 on 2025-05-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0027_alter_appointeddoctor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointeddoctor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20, null=True),
        ),
    ]
