# Generated by Django 5.1.6 on 2025-05-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0029_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
